name: CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, pdo_mysql

    - name: Install Dependencies
      run: composer install --no-dev --prefer-dist --no-progress

    - name: Build Assets
      run: |
        # Add any build steps here if needed
        echo "Building assets..."

    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /var/www/flights
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php vendor/bin/doctrine-migrations migrate --no-interaction
          # Add any additional deployment steps here
          echo "Deployment completed"
