name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    name: Tests & Quality Checks
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: flights
          MYSQL_USER: slim
          MYSQL_PASSWORD: slim
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u slim --password=slim"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s

    strategy:
      matrix:
        php-versions: ['8.2', '8.3']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, pdo_mysql
        coverage: xdebug

    - name: Validate composer.json
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: |
        composer config platform.php 8.2
        composer install --prefer-dist --no-progress --no-suggest

    - name: Wait for MySQL
      run: |
        while ! mysql -h"127.0.0.1" -P"3307" -u"slim" -p"slim" -e "SELECT 1" >/dev/null 2>&1; do
          echo "Waiting for MySQL to be ready..."
          sleep 1
        done
        echo "MySQL is ready!"
        
    - name: Run Database Migrations
      run: |
        cp migrations-db.ci.php migrations-db.php
        mysql -h"127.0.0.1" -P"3307" -u"slim" -p"slim" -e "SHOW DATABASES;"
        composer migrations:migrate --no-interaction -vvv
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3307
        DB_DATABASE: flights
        DB_USERNAME: slim
        DB_PASSWORD: slim
        MYSQL_PWD: slim

    - name: Check Code Style
      run: |
        vendor/bin/phpcs --standard=PSR12 src/ tests/

    - name: Static Analysis
      run: |
        vendor/bin/phpstan analyse src tests --level=5

    - name: Run Tests
      run: |
        vendor/bin/phpunit --coverage-text
