name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    name: Tests & Quality Checks
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: flights
          MYSQL_USER: slim
          MYSQL_PASSWORD: slim
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, pdo_mysql
        coverage: xdebug

    - name: Validate composer.json
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Database Migrations
      run: |
        composer migrations:migrate --no-interaction

    - name: Check Code Style
      run: |
        vendor/bin/phpcs --standard=PSR12 src/ tests/

    - name: Static Analysis
      run: |
        vendor/bin/phpstan analyse src tests --level=5

    - name: Run Tests
      run: |
        vendor/bin/phpunit --coverage-text
